//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISRPO_PR15_Cherednichenko.ApplicationData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SofaEntities : DbContext
    {
        private static SofaEntities _context;

        public static SofaEntities GetContext()
        {
            if (_context == null)
                _context = new SofaEntities();
            return _context;
        }

        public SofaEntities()
            : base("name=SofaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Colour> Colour { get; set; }
        public virtual DbSet<Matherial> Matherial { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tovars> Tovars { get; set; }
    }
}
